# Production API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  reload: false
  log_level: "info"
  
  # Security
  cors_origins:
    - "http://localhost:3000"
    - "https://yourdomain.com"
  
  # Rate limiting
  rate_limit:
    requests_per_hour: 100
    training_requests_per_hour: 10
    generation_requests_per_hour: 50
    
  # File handling
  max_file_size_mb: 100
  temp_file_cleanup_hours: 24
  
  # Job management
  max_concurrent_training: 2
  max_concurrent_generation: 4
  max_concurrent_evaluation: 3
  job_cleanup_days: 30
  
  # Directories
  data_directory: "api_data"
  upload_directory: "api_data/uploads"
  output_directory: "api_data/outputs"
  model_directory: "api_data/models"
  
database:
  path: "api_data/jobs.db"
  backup_enabled: true
  backup_interval_hours: 6
  
monitoring:
  enable_metrics: true
  metrics_endpoint: "/metrics"
  health_check_interval: 30
  
  # OpenTelemetry (optional)
  otel_enabled: false
  otel_endpoint: "http://localhost:4317"
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "api_data/logs/api.log"
  max_file_size_mb: 10
  backup_count: 5
  
models:
  # Default hyperparameters for each model
  ganeraid:
    default_epochs: 100
    max_epochs: 1000
    default_lr_g: 0.001
    default_lr_d: 0.001
    
  ctgan:
    default_epochs: 300
    max_epochs: 1000
    default_batch_size: 500
    
  tvae:
    default_epochs: 300
    max_epochs: 1000
    default_batch_size: 500
    
# Environment-specific overrides
development:
  api:
    reload: true
    log_level: "debug"
  logging:
    level: "DEBUG"

production:
  api:
    workers: 8
    reload: false
  logging:
    level: "INFO"
  database:
    backup_enabled: true