"""
Documentation generation utilities for results folders
"""


def create_section2_readme(results_path, dataset_id, timestamp):
    """
    Create README.md explaining Section 2 output files

    Parameters:
    -----------
    results_path : str
        Path to Section 2 results directory
    dataset_id : str
        Dataset identifier
    timestamp : str
        Session timestamp

    Returns:
    --------
    str : Path to created README file
    """
    readme_content = f"""# Section 2: Exploratory Data Analysis - Output Files

This folder contains EDA results performed before model training.

## Visualizations

- **correlation_heatmap.png**: Pairwise correlations between numeric features. Identifies multicollinearity and relationships. Font size adjusts dynamically based on number of features.

- **feature_distributions.png** (or **feature_distributions_part1.png**, **part2.png**, ...): Histograms of each numeric feature. Multiple files generated for datasets with many features (6 features per file in 3x2 grid for readability).

## Data Analysis CSV Files

- **correlation_matrix.csv**: Raw correlation coefficients between all numeric features (-1 to +1 scale).

- **target_correlations.csv**: Correlations between each feature and target variable, sorted by absolute strength. Identifies most predictive features.

- **column_analysis.csv**: Comprehensive statistics per column including data type, missing values, unique values, and descriptive statistics (mean, std, min, max).

- **target_balance_metrics.csv**: Class distribution analysis for target variable, including counts, proportions, and balance metrics. Important for understanding class imbalance.

- **target_analysis.csv**: Detailed target variable characteristics and distribution.

## Purpose

These files provide baseline understanding of:
- Data quality (missing values, distributions)
- Feature relationships (correlations)
- Target characteristics (class balance)
- Potential preprocessing needs

## Next Steps

After reviewing these files, proceed to Section 3 for synthetic data generation and model evaluation.

---
*Generated by Clinical Synthetic Data Generation Framework*
*Dataset: {dataset_id}*
*Date: {timestamp}*
"""

    readme_path = f"{results_path}/README.md"
    with open(readme_path, 'w', encoding='utf-8') as f:
        f.write(readme_content)
    print(f"[DOCS] Created: Section-2/README.md")
    return readme_path


def create_section3_main_readme(results_path, dataset_id, timestamp):
    """Create main README for Section 3 root folder"""
    readme_content = f"""# Section 3: Model Evaluation - Output Files

This folder contains evaluation results for all trained synthetic data generation models.

## Structure

Each model has its own subfolder:
- **CTGAN/** - Conditional Tabular GAN results
- **CTABGAN/** - CTAB-GAN results
- **CTABGANPLUS/** - CTAB-GAN+ results
- **GANERAID/** - GANerAid results
- **COPULAGAN/** - CopulaGAN results
- **TVAE/** - Tabular Variational Autoencoder results

## Common Files Per Model

### CSV Files
- **evaluation_summary.csv** - High-level quality scores
- **statistical_similarity.csv** - Feature-level similarity metrics
- **mode_collapse_analysis.csv** - Categorical variable diversity check (if applicable)

### Visualizations
- **correlation_comparison.png** - Side-by-side heatmaps (real vs synthetic)
- **distribution_comparison_partN.png** - Overlaid histograms per feature
- **pca_comparison_with_outcome.png** - Principal component analysis
- **training_loss.png** - Training loss over epochs (per model folder, if available)
- **training_loss_comparison_all_models.png** - Loss comparison across all models (Section-3 root, if available)
- **mode_collapse_summary.png** - Category coverage visualization (if mode collapse detected)
- **mutual_information_comparison.png** - MI preservation analysis (if computed)

## Column Definitions

### evaluation_summary.csv

| Column | Description |
|--------|-------------|
| model | Model name identifier |
| avg_statistical_similarity | Mean/std matching across features (0-1, higher better) |
| avg_js_similarity | Jensen-Shannon divergence similarity (0-1, 1=identical distributions) |
| correlation_preservation | Pearson correlation between real and synthetic correlation matrices (0-1) |
| overall_pca_similarity | Average similarity across principal components (0-1) |
| ml_utility | Cross-training accuracy average (0-1) |
| overall_quality_score | Composite quality score (0-1) |
| quality_assessment | Categorical: EXCELLENT (≥0.8), GOOD (≥0.6), FAIR (≥0.4), POOR (<0.4) |
| mode_collapse_detected | Boolean: True if any categorical variable lost diversity |
| mode_collapse_count | Number of features with mode collapse |
| mutual_information_preservation | MI score preservation (0-1, if computed) |

### statistical_similarity.csv

| Column | Description |
|--------|-------------|
| column | Feature name |
| real_mean | Mean value in real dataset |
| synthetic_mean | Mean value in synthetic dataset |
| mean_similarity | How closely means match (0-1, normalized by std) |
| std_similarity | Ratio of standard deviations (0-1, 1=perfect match) |
| overall_similarity | Average of mean_similarity and std_similarity |

### mode_collapse_analysis.csv

| Column | Description |
|--------|-------------|
| column | Categorical feature name |
| real_unique_count | Number of unique categories in real data |
| synthetic_unique_count | Number of unique categories in synthetic data |
| category_coverage | Proportion of real categories present in synthetic (0-1) |
| distribution_similarity | 1 - Total Variation Distance for category frequencies (0-1) |
| mode_collapse_flag | Boolean: True if collapse detected |
| collapse_severity | Severe / Moderate / Mild / None |
| missing_categories | List of real categories absent in synthetic |
| extra_categories | List of synthetic categories not in real |

## Interpretation Guide

### pca_comparison_with_outcome.png (4-panel visualization)

**Top-Left (Real Data PC1 vs PC2)**: Scatter plot of real data points in principal component space. Colors indicate target values. Shows natural clustering.

**Top-Right (Synthetic Data PC1 vs PC2)**: Scatter plot of synthetic data. Should exhibit similar clustering patterns and color distribution if synthetic data captures relationships well.

**Bottom-Left (Explained Variance)**: Bar chart showing variance captured by each principal component. Real and synthetic should have similar distributions if structure preserved.

**Bottom-Right (Component Similarity)**: Correlation between real and synthetic for each PC (0-1 scale). Higher scores (>0.7) indicate better structural preservation.

**What to look for**:
- Similar scatter patterns (top-left vs top-right)
- Comparable color distributions (target relationships preserved)
- Similar explained variance ratios (bottom-left)
- High component similarity scores (bottom-right, ideally >0.7)

## Usage

Compare evaluation_summary.csv across all models to identify best performers. Review model-specific visualizations to understand strengths and weaknesses.

---
*Generated by Clinical Synthetic Data Generation Framework*
*Dataset: {dataset_id}*
*Date: {timestamp}*
"""

    readme_path = f"{results_path}/README.md"
    with open(readme_path, 'w', encoding='utf-8') as f:
        f.write(readme_content)
    print(f"[DOCS] Created: Section-3/README.md")
    return readme_path


def create_section3_model_readme(results_dir, model_name, quality_score, quality_rating,
                                 dataset_id, timestamp):
    """Create model-specific README"""
    readme_content = f"""# {model_name.upper()} - Synthetic Data Quality Evaluation

## Model: {model_name.upper()}

## Generated Files

- **evaluation_summary.csv**: Overall quality metrics
- **statistical_similarity.csv**: Per-feature similarity analysis
- **correlation_comparison.png**: Correlation matrix comparison
- **distribution_comparison_partN.png**: Feature distribution comparisons
- **pca_comparison_with_outcome.png**: Principal component analysis

## Quick Assessment

- **Overall Quality Score**: {quality_score:.3f}
- **Quality Rating**: {quality_rating}

Refer to parent folder README.md for detailed column definitions and interpretation guidance.

---
*Dataset: {dataset_id}*
*Generated: {timestamp}*
"""

    readme_path = f"{results_dir}/README.md"
    with open(readme_path, 'w', encoding='utf-8') as f:
        f.write(readme_content)
    return readme_path


def create_section5_readme(results_path, dataset_id, timestamp):
    """
    Create README for Section 5 outputs

    Parameters:
    -----------
    results_path : str
        Path to Section 5 results directory
    dataset_id : str
        Dataset identifier
    timestamp : str
        Session timestamp

    Returns:
    --------
    str : Path to created README file
    """
    readme_content = f"""# Section 5: Final Model Comparison - Output Files

This folder contains comprehensive performance comparison across all synthetic data generation models.

## CSV Files

### Model Performance Metrics

- **trts_detailed_results.csv**: Comprehensive classification metrics for all TRTS scenarios
  - **Columns**: Model, Scenario, Accuracy, F1_Score, Precision, Recall, Sensitivity, Specificity, NPV, FPR, FNR, Balanced_Accuracy, MCC, Cohen_Kappa, AUROC, AUPRC, Average_Precision, Training_Time_Sec
  - **Scenarios**:
    - TRTR (Train Real, Test Real): Baseline performance
    - TRTS (Train Real, Test Synthetic): Synthetic data validity
    - TSTR (Train Synthetic, Test Real): Model utility
    - TSTS (Train Synthetic, Test Synthetic): Internal consistency
  - **Use**: Compare model utility and validity across all synthetic data generators

- **privacy_metrics.csv**: Privacy assessment and risk analysis for all models
  - **Key Columns**:
    - Model: Model name identifier
    - nn_dist_synth_to_real_mean: Average nearest neighbor distance (synthetic → real)
    - nn_dist_real_to_synth_mean: Average nearest neighbor distance (real → synthetic)
    - memorization_risk: Proportion of synthetic samples too similar to real data (0-1, lower better)
    - reidentification_rate: Risk of re-identifying individuals (0-1, lower better)
    - uniqueness_ratio: Diversity of synthetic data (0-1, higher better)
    - distance_distribution_divergence: KS statistic comparing distance distributions
  - **Use**: Assess privacy risks and data diversity for each model

## Visualizations

### Performance Visualizations

- **trts_comprehensive_analysis.png**: 4-panel TRTS performance comparison
  - **Panel 1 (Top-Left)**: Overall performance across all TRTS scenarios
  - **Panel 2 (Top-Right)**: Statistical similarity and quality metrics
  - **Panel 3 (Bottom-Left)**: ML utility metrics (cross-training accuracy)
  - **Panel 4 (Bottom-Right)**: Training time comparison
  - **Purpose**: Identify best-performing models at a glance

### Privacy Visualizations

- **privacy_dashboard.png**: 4-panel privacy metrics comparison
  - **Panel 1 (Top-Left)**: Memorization risk (lower is better)
  - **Panel 2 (Top-Right)**: Re-identification rate (lower is better)
  - **Panel 3 (Bottom-Left)**: Uniqueness ratio (higher is better)
  - **Panel 4 (Bottom-Right)**: Nearest neighbor distance comparison
  - **Purpose**: Visual privacy risk assessment across all models

## Interpretation Guide

### TRTS Scenario Interpretation

- **TRTR ≈ TRTS**: Synthetic data has similar statistical properties to real data
- **TRTR ≈ TSTR**: Synthetic data preserves predictive relationships (high utility)
- **TSTR > TRTR**: Synthetic data may have captured additional patterns (or overfitting)
- **TSTR << TRTR**: Synthetic data lost important relationships (low utility)

### Privacy Metric Thresholds

- **Memorization Risk**:
  - < 0.05: Excellent (low risk)
  - 0.05-0.10: Good (moderate risk)
  - > 0.10: High risk (review model)

- **Re-identification Rate**:
  - < 0.01: Excellent (very low risk)
  - 0.01-0.05: Acceptable (low risk)
  - > 0.05: High risk (not recommended for release)

- **Uniqueness Ratio**:
  - > 0.90: Excellent diversity
  - 0.70-0.90: Good diversity
  - < 0.70: Low diversity (potential mode collapse)

## Usage Workflow

1. **Review trts_comprehensive_analysis.png**: Identify top-performing models
2. **Check privacy_dashboard.png**: Verify acceptable privacy risk
3. **Examine trts_detailed_results.csv**: Deep dive into specific metrics
4. **Validate with privacy_metrics.csv**: Confirm quantitative privacy thresholds
5. **Select best model**: Balance performance vs privacy trade-offs

## Model Selection Criteria

Recommended decision matrix:
1. **High Utility + Low Privacy Risk**: Ideal - use this model
2. **High Utility + High Privacy Risk**: Consider privacy-enhancing techniques
3. **Low Utility + Low Privacy Risk**: Safe but not useful - try different model
4. **Low Utility + High Privacy Risk**: Avoid - worst of both worlds

---
*Generated by Clinical Synthetic Data Generation Framework*
*Dataset: {dataset_id}*
*Date: {timestamp}*
"""

    readme_path = f"{results_path}/README.md"
    with open(readme_path, 'w', encoding='utf-8') as f:
        f.write(readme_content)
    print(f"[DOCS] Created: Section-5/README.md")
    return readme_path
